AddCSLuaFile("cl_dcardlist.lua")
AddCSLuaFile("cl_dmodel_card.lua")
AddCSLuaFile("cl_dnumsliderbet.lua")
AddCSLuaFile("cl_init.lua")
AddCSLuaFile("cl_panel_help.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_player.lua")

include("shared.lua")
include("sh_player.lua")
